version: "3.1"
services:
  web:
    build: .
    env_file: .env
    command: "npm start"
    volumes:
      - ./public:/notifier/public
    ports:
      - 3000:3000
    depends_on:
     - redis
     - mongoDB
  sockjs:
    build:
      context: ./notifier
    command: "npm start"
    depends_on:
      - redis
      - mongoDB
    ports:
      - 4000:4000
  redis:
    image: redis:alpine
  mongoDB:
    image: mongo:3.5
    ports:
      - 27017:27017

