version: "3.1"
services:
  lb:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.warehouse.conf:/etc/nginx/conf.d/default.conf
      - ./wait-for:/wait/wait-for
    depends_on:
      - web
  web:
    build: .
    env_file: .env
    command: "npm start"
    volumes:
      - ./public:/notifier/public
    ports:
      - 3000:3000
    depends_on:
     - redis
     - mongoDB
  sockjs:
    build:
      context: ./notifier
    command: "npm start"
    depends_on:
      - redis
      - mongoDB
    ports:
      - 4000:4000
  redis:
    image: redis:alpine
  mongoDB:
    image: mongo:3.5
    ports:
      - 27017:27017

