// Sockjs events
export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_FETCH_NOTIFICATION_HISTORY = 'USER_FETCH_NOTIFICATION_HISTORY';
export const NOTIFICATION_HISTORY = 'NOTIFICATION_HISTORY';
export const NOTIFICATION_HISTORY_EMPTY = 'NOTIFICATION_HISTORY_EMPTY';
export const MESSAGES_DELETED = 'MESSAGES_DELETED';
export const BULK_MESSAGES_DELETED = 'BULK_MESSAGES_DELETED';
export const INVALID_JSON = 'INVALID_JSON';
export const AUTH_ERROR = "AUTH_ERROR";
export const ERROR = 'ERROR';

export const NOTIFICATION_RECEIVED_ACK = 'NOTIFICATION_RECEIVED_ACK';
export const NOTIFICATION_BULK_RECEIVED_ACK = 'NOTIFICATION_BULK_RECEIVED_ACK';

// Worker events
export const WORKER_NOTIFICATION_RECEIVED = 'WORKER_NOTIFICATION_RECEIVED';