// Sockjs events
export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const INVALID_JSON = 'INVALID_JSON';
export const AUTH_ERROR = "AUTH_ERROR";
export const ERROR = 'ERROR';

export const NOTIFICATION_RECEIVED_ACK = 'NOTIFICATION_RECEIVED_ACK';

// Worker events
export const WORKER_NOTIFICATION_RECEIVED = 'WORKER_NOTIFICATION_RECEIVED';